fixes:
  - "ballerina/http/**/::../ballerina/"
  - "io/ballerina/stdlib/http/compiler/::./compiler-plugin/src/main/java/io/ballerina/stdlib/http/compiler/"

ignore:
  - "ballerina-tests"
  - "test-utils"
  - "compiler-plugin/src/main/java/io/ballerina/stdlib/http/compiler/oas" # This is covered in OpenAPI tool

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: 80
