[package]
org = "ballerina"
name = "http_tests"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../http-native/build/libs/http-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "http"
version = "@project.version@"
