[container.image]
repository = "ballerina"
name = "h2_h1c_passthrough"
base = "adoptopenjdk:11.0.11_9-jre-openj9-0.26.0-focal"

[[container.copy.files]]
sourceFile="./security/ballerinaKeystore.p12"
target="/home/ballerina/security/ballerinaKeystore.p12"

[cloud.deployment]
min_memory = "256Mi"
max_memory = "512Mi"
min_cpu = "200m"
max_cpu="1000m"

[cloud.deployment.autoscaling]
min_replicas = 1
max_replicas = 1
