resources:
  - h1_accesslog_enabled.yaml
  - ingress.yaml
  - netty-backend.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: h1-accesslog-enable-deployment
- path: secret-patch.yaml
  target:
    version: v1
    kind: Secret
