resources:
  - accesslog_enabled.yaml
  - ingress.yaml
  - netty-backend.yaml
patches:
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: accesslog-enabl-deployment
