[package]
org = "ballerina"
name = "integration_tests"
version = "2.16.1"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "http-test-utils"
scope = "testOnly"
path = "../test-utils/build/libs/http-test-utils-2.16.1-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
path = "./lib/io-native-1.8.0.jar"
