name: GraalVM Check

on:
    workflow_dispatch:
        inputs:
            lang_tag:
                description: Branch/Release Tag of the Ballerina Lang
                required: true
                default: master
            lang_version:
                description: Ballerina Lang Version (If given ballerina lang buid will be skipped)
                required: false
                default: ''
            native_image_options:
                description: Default native-image options
                required: false
                default: ''
            build_properties:
                description: Additional build properties
                required: false
                default: ''

    schedule:
        -   cron: '30 18 * * *'
        
    pull_request:
        branches: 
            - master
            - 2201.7.x
            - 2201.8.x
            - 2201.9.x
            - java21
        types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
    cancel-in-progress: true

jobs:
    call_stdlib_workflow:
        name: Run StdLib Workflow
        if: ${{ github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository_owner == 'ballerina-platform') }}
        uses: ballerina-platform/ballerina-library/.github/workflows/build-with-bal-test-graalvm-template.yml@java21
        with:
            lang_tag: 'java21'
            lang_version: '2201.10.0-20241019-091600-89e54c08'
            native_image_options: '-J-Xmx7G ${{ inputs.native_image_options }}'
            additional_ubuntu_build_flags: '-x :http-native:test -x :http-compiler-plugin-tests:test ${{ inputs.build_properties }}'
            additional_windows_build_flags: '-x :http-native:test -x :http-compiler-plugin-tests:test ${{ inputs.build_properties }}'
            java_tool_options: '-Dfile.encoding=UTF8'
