name: Publish to the Ballerina central

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        options:
          - CENTRAL
          - DEV CENTRAL
          - STAGE CENTRAL

jobs:
  call_workflow:
    name: Run Central Publish Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/central-publish-template.yml@java21
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
