name: On demand build without tests

on:
  workflow_dispatch:

jobs:
  call_workflow:
    name: Run Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    uses: ballerina-platform/ballerina-library/.github/workflows/build-timestamp-master-template.yml@java21
    with:
      additional-build-flags: '-x check -x test'
    secrets: inherit
