name: PR Build

on: [pull_request]

jobs:
  call_workflow:
    name: Run PR Build Workflow
    if: ${{ github.repository_owner == 'ballerina-platform' }}
    permissions:
      contents: read
      pull-requests: write
    uses: daneshk/ballerina-library/.github/workflows/pull-request-build-template.yml@pr-build-bal-scan
    secrets: inherit
